# Generated by Django 5.0.3 on 2024-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_weight_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='severity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
